version: '3.8'

services:
  main:
    build: ./
    command: ./main
    ports:
    - 4000:4000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=alimzhan125


  db:
    restart: always
    image: library/postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
    - 8001:5432
    environment:
      - DB_PASSWORD=alimzhan125